### ISSUE TITLE
`where` first type declaration is messing the completion of field param when other params are filled

### ISSUE THREAD

**Issue by SrBrahma** [kossnocorp/typesaurus#101]
Images to better explain:

### When writing first param. Working as intended:

![image](https://user-images.githubusercontent.com/28177550/141196096-6f4212b8-f2e9-4d20-92f7-f4f3ff5c3014.png)

### When filling first param when others are already filled. Intellisense not working, may enter invalid fields without TS error.

![image](https://user-images.githubusercontent.com/28177550/141195965-ee6644b1-a5a8-4f5d-aff0-eb4581571786.png)

### I have found out that if I remove the first where type declaration in the .d.ts of this lib, it gets fixed.

![image](https://user-images.githubusercontent.com/28177550/141196482-82e25061-e203-4996-82b3-64b8d86f766e.png)

### The problematic where that causes it and that I removed to fix it, as shows the previous image

![image](https://user-images.githubusercontent.com/28177550/141196450-e33829c0-9138-4770-b4d1-efaec1411318.png)

**Comment by SrBrahma** [comment]
The problematic type is the DocId, that is declared just as `declare class DocId {}`, and that {} is probably being interpreted as any non-nullish value, as it says when we `type A = {}`:

```
Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.
```

Proof of that is that I can just write any type of value in the first param when the other params are filled, except null.

![image](https://user-images.githubusercontent.com/28177550/141197922-44629861-d32c-4b2b-a184-d079cb207bd4.png)

![image](https://user-images.githubusercontent.com/28177550/141197998-02026406-92b5-4052-8cba-bd788acd16c9.png)

I am using the alpha version of the lib.

**Comment by kossnocorp** [comment]
Fixed with v10
