### ISSUE TITLE
Manual Timestamps are being changed

### ISSUE THREAD

**Issue by SrBrahma** [kossnocorp/typesaurus#105]
Example:

```ts
await set(users, 'a', {
  a: new Date(0),
  b: firebase.firestore.Timestamp.fromDate(new Date(0)),
} as any);
await db.doc('users/b').set({ c: firebase.firestore.Timestamp.fromDate(new Date(0)) });
```

![image](https://user-images.githubusercontent.com/28177550/142061365-6e76bdc0-4dc5-45ea-97c8-b5d5c571acf8.png)
![image](https://user-images.githubusercontent.com/28177550/142061378-3178669d-c97e-4d4f-933c-c58701d19c80.png)

It's not trivial. It's not allowing my query that compares Date to work, ex `where('myField', '>', new Date(0)),`. The query doesn't work in the {_seconds} object, only when it's a proper Timestamp.

Using v8 version.

I am out of time currently, I will try to quickly fix it and make a PR if I can do it.

**Comment by SrBrahma** [comment]
I though it was a Emulator issue: https://github.com/firebase/firebase-tools/issues/3900

**Comment by KoreanThinker** [comment]
@SrBrahma is there a temporary solution??

**Comment by kossnocorp** [comment]
I don't think it's relevant, but if it does please open a new issue with more details
