### ISSUE TITLE
Provide live examples for Firestore layout to Typesaurus schema conversion

### ISSUE THREAD

**Issue by MRDGH2821** [kossnocorp/typesaurus#123]
I didn't understand how to create a schema when I already have some data in Cloud Firestore.
I mean to say, I did not understand how to translate the layout I see in Firebase console to the schema in typesaurus.

So it would be nice to see a comparative study & conversion of Cloud Firestore's DB _layout_ into Typesaurus schema.

I use Cloud firestore in discord bots, so here is the _layout_ I see in Firestore console (given in json format):

```json
{
  "servers": {
    "<server_id_int_1>": {
      "name": "<server_name_1>",
      "id": "<server_id_int_1>",
      "date": "<server_date_1>"
    },
    "<server_id_int_2>": {
      "name": "<server_name_2>",
      "id": "<server_id_int_2>",
      "date": "<server_date_2>"
    }
  },

  "webhooks": {
    "<server_id_int_1>": "<webhook_url_1>",
    "<server_id_int_2>": "<webhook_url_2>"
  },
  "user_preferences": {
    "<user_id_int_1>": {
      "user_id": "<user_id_int_1>",
      "settings": {
        "feature_1": "true",
        "feature_2": "false"
      }
    }
  }
}
```
The value inside `<` & `>` indicate document ID with respect to Firestore. And with respect to the discord bot, it refers to specific values (not the autogenerated values).

**Comment by kossnocorp** [comment]
Hey! First of all, which version are you using? Please make sure you use the latest RC (10). It's ready for launch. I'm just waiting for the blog post announcement to be published.

The docs are here: https://next.typesaurus.com/get-started/

> So it would be nice to see a comparative study & conversion of Cloud Firestore's DB layout into Typesaurus schema.

That would be nice indeed! I'll keep it in mind and probably write a doc about that in the future.

---

Regarding your JSON, sorry, I'm a bit confused. Is it a single document, or do you describe collections like that?

I assume that it's a document as `webhooks` can't be a document (unless I missed something fundamental), so here's the example:

```ts
import { schema } from "typesaurus";

const db = schema(($) => ({
  docs: $.collection<Doc>(),
}));

interface Doc {
  servers: Servers;
  webhooks: Webhooks;
  user_preferences: UserPreferences;
}

type Servers = Record<number, Server>;

interface Server {
  name: string;
  id: number;
  date: Date;
}

type Webhooks = Record<number, string>;

type UserPreferences = Record<number, UserPreference>;

interface UserPreference {
  user_id: number;
  settings: Settings;
}

type Settings = Record<string, string>;
```

Of course, it's a very simplified example, but if you could please tell me more, I'll try to help. That would be great. I would also appreciate it if you can read the "Designing schema" section in the docs and see if it answers your questions: https://next.typesaurus.com/design/best-practices/

**Comment by MRDGH2821** [comment]
Actually the webhooks part was a mistake from my side 😅 

So what I mean by live example is this:

![Firestore Servers collection](https://github.com/kossnocorp/typesaurus/assets/46621001/181e500c-f95c-415f-9d52-b499cad4910d)

There are 3 collections: `servers`, `users` & `express-sessions`. Focusing on `servers` & `users` for now.

So, inside the collection, I have server id as the "document" name & it has document of 3 properties a.k.a "fields".

Then there's `users` collection:
![Firestore Users Collection](https://github.com/kossnocorp/typesaurus/assets/46621001/02149afe-a454-4710-a517-8e615eed17a8)
This one has an firestore autogenerated ID (by mistake) which I do not want (I was looking around & checking out stuff)
And the other document has user id as the "document" name with 2 "fields".


What I need is a direct/live comparision/examples to convert existing firestore _layout_ into typesaurus schema.
Suppose this is the schema I give you, how would you translate it into typesaurus schema?

**Comment by kossnocorp** [comment]
@MRDGH2821 do you mind if I write a doc using your example and link to this issue? I think your schema is very straightforward but has some nuances, like `express-sessions` having a dash in it, so it will be a good quickstart example.

**Comment by MRDGH2821** [comment]
> @MRDGH2821 do you mind if I write a doc using your example and link to this issue? I think your schema is very straightforward but has some nuances, like `express-sessions` having a dash in it, so it will be a good quickstart example.

I have no problems, as long as those ID values are not in the example.

(Maybe I should have properly censored it from my side😬😅)

**Comment by MRDGH2821** [comment]
Can I see how my existing firestore db console screenshot translates to Typesaurus schema?🤔

I may have missed the doc update, so is there any link/reference?🤔

**Comment by kossnocorp** [comment]
Hey, thank you for waiting! Here's the doc I promised: https://next.typesaurus.com/design/adopting. Please let me know if you have more questions or any feedback on this and other schema design docs on the website.

**Comment by MRDGH2821** [comment]
> Here’s an example of a simple real-life database. The top-level properties are the collections, {fooId} are the dynamic ids.

In the guide, I'm confused about `dynamic ids`, are these IDs autogenerated by firebase when a new entry is added?

If yes, then how can I enter a custom ID?🤔
My firebase DB screenshot has custom IDs 

If no, then I feel I haven't understood the schema definition in the docs. Maybe I need to experiment a little after which I will come to understand 🤔
