### ISSUE TITLE
Firestore peers produce inevitable unmet-dependancy warnings.

### ISSUE THREAD

**Issue by gabeklein** [kossnocorp/typesaurus#17]
Due to the dual-environment nature of this package, it's understandable why `firebase-admin`, `@google-cloud/firestore` and `firestore` are peer-required. However, I would advocate that none of these are explicitly.

**Comment by kossnocorp** [comment]
So you suggest removing peer dependencies at all?

**Comment by kossnocorp** [comment]
I just noticed the issue title, and now it makes sense. You're right about that. I'll remove it, no need for useless warnings.

I can't help but wonder where peer dependencies are useful at all?

**Comment by gabeklein** [comment]
Yea, sorry for the terse writeup though, I posted completely by accident before finishing my justifications for this change.

Anyway, yes I do and here's why. First of all the purpose of peer dependancies is to inform a consuming developer that some external package must be installed for a package to function properly. In this package's case, we have a situation where a different dependancy may be require depending on the environment. I read into your source a little bit, and see you're using `browser` and `main` requires (quite awesome!), but it puts this package also in a little bit of a pickle, making it impossible to suppress the `unmet peer dependancy` warnings without making a quite hefty cloud-interop package a dependancy (and installed useless by CI, etc.).

**Comment by gabeklein** [comment]
Also, I did check! `@google-cloud/firestore` is not even required in a node environment anymore. Apparently `firebase-admin` now ships that internally.

**Comment by kossnocorp** [comment]
No worries, yeah, I agree with you. I will do the change with the next version.

**Comment by kossnocorp** [comment]
Closed by https://github.com/kossnocorp/typesaurus/pull/19
