### ISSUE TITLE
Simple pagination with offset

### ISSUE THREAD

**Issue by mellet** [kossnocorp/typesaurus#24]
Could not find it in the documentation, but would be great if we could use [offset()](https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/firestore/Query.html#offset-int-) instead of `startAfter` / `startBefore` etc for paginating documents.

Example from my firestore query:

```typescript
let page = Number(req.query.page);
let limit = Number(req.query.limit);

// Calculate offset based on page and limit
let offset = limit * (page - 1);

let query = firestore()
      .collection("users")
      .orderBy("createdAt", "desc")
      .offset(offset)
      .limit(limit);
```

**Comment by kossnocorp** [comment]
Hm, interestingly enough, there's [no offset in the JavaScript web API](https://firebase.google.com/docs/reference/js/firebase.firestore.Query), but it's [present in Node.js](https://googleapis.dev/nodejs/firestore/latest/Query.html#offset). I'll take a look into how I can make it work.

**Comment by lucasavila00** [comment]
Note: It's not recommended to use offset at the client:

> There are no additional costs for using cursors, page tokens, and limits. In fact, these features can help you save money by reading only the documents that you actually need.
> 
> However, when you send a query that includes an offset, you are charged a read for each skipped document. For example, if your query uses an offset of 10, and the query returns 1 document, you are charged for 11 reads. Because of this additional cost, you should use cursors instead of offsets whenever possible.
> 

[source](https://firebase.google.com/docs/firestore/pricing)

Also a comment by a member of firebase team: https://github.com/firebase/firebase-js-sdk/issues/479#issuecomment-364216376

**Comment by kossnocorp** [comment]
@lucasavila00 ah, that's interesting! So it basically reads the number of documents specified as the argument, so further you go more expensive the query becomes. I'm wondering why the heck they did add it to firebase-admin then?

I can possibly add the function and throw an exception in the browser environment but that would encourage a bad pattern.

@mellet WDYT?

**Comment by mellet** [comment]
@lucasavila00 @kossnocorp 

Interesting, I wonder if the extra read costs also occur on the firebase-admin sdk when using offset.

I tried making the pagination with typesaurus, but could not figure out how I could paginate as I show above. If you have an example of how I could do it I don't need the offset.

I was looking at this [example](https://firebase.google.com/docs/firestore/query-data/query-cursors#paginate_a_query) (for nodejs).
I tried writing that with typesaurus but it seemed like I was doing a lot of documents reads to make it work.

**Comment by lucasavila00** [comment]
@mellet this is an issue with firestore api, there isn't much of a work around.
Say you have a list of users ordered by the year they were born;
Then you could query by the year they were born (ex: year >= 1994) but if you have 1000 like this then there is no easy way to paginate between them (ex: year >= 1994 but skip the first 25)

This video touches the topic: https://www.youtube.com/watch?v=IdKEhWAV-kE

If you really need to paginate data and cursors are not enough for you I'd suggest not using firestore then.

**Comment by kossnocorp** [comment]
> Interesting, I wonder if the extra read costs also occur on the firebase-admin SDK when using offset.

There should be no difference between how firebase-admin and the web SDK works. I think it's just web API that is more open to attacks, unlike Node.js, where you fully control the environment. However, if you get the page number from user (URL) then it could be problematic and potentially expensive.

I'm not entirely sure how it works, and I'm going to dig it further, but from what I know, there's no id index like in traditional SQL databases. However, there're indexes for every field, so instead of offsetting, Firestore finds a specific document by a field value using `startAfter`, `startAt`, `endAt` and `endBefore`.

So answering your questions, there's no direct translation of `offset`, but rather an alternative approach with cursors. The topic is described in detail in [the Firestore docs](https://firebase.google.com/docs/firestore/query-data/query-cursors).

**Comment by kossnocorp** [comment]
@lucasavila00 thank you for the link to the video, it's helpful!

**Comment by kossnocorp** [comment]
I made a research and figured out that offset is a Trojan Horse: https://firebeast.dev/tips/do-not-use-offset.

For example, this code will produce 2900 document reads:

```
import * as admin from 'firebase-admin'

admin.initializeApp()

admin
  .firestore()
  .collection('pages')
  .orderBy('number')
  .limit(1)
  .offset(2900)
  .get()
```
I don't think I should let people shoot into their feet, so I'm closing it.
