### ISSUE TITLE
Work with Gatsby (on node without firebase-admin)

### ISSUE THREAD

**Issue by lucasavila00** [kossnocorp/typesaurus#25]
I'm having issues building a Gatsby site with typesaurus.
I don't actually use typesaurus while doing SSR, only on the client.

The issue is that if I don't have firebase-admin installed while doing SSR webpack will have an issue because it cannot find firebase-admin.

If I install it webpack will complain about not being able to process some ".proto" files.

I was able to fix it by patching the built node.js adaptor to be the same as the browser but it cannot export FirestoreDocumentReference, FirestoreTimestamp and FirestoreFieldValue or it will error:
```
 WebpackError: TypeError: Cannot read property 'DocumentReference' of undefined
```

```javascript
// typesaurus/adaptor/node.js that works with gatsby
// Its a copy of /adaptor/browser.js with some stuff comented out (see at the bottom)
'use strict'
/**
 * Browser Firestore adaptor.
 */
var __importStar =
  (this && this.__importStar) ||
  function(mod) {
    if (mod && mod.__esModule) return mod
    var result = {}
    if (mod != null)
      for (var k in mod)
        if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k]
    result['default'] = mod
    return result
  }
Object.defineProperty(exports, '__esModule', { value: true })
const firebase = __importStar(require('firebase/app'))
require('firebase/firestore')
function store() {
  const firestore = firebase.firestore()
  // At the moment, the browser's Firestore adaptor doesn't support getAll.
  // Get rid of the fallback when the issue is closed:
  // https://github.com/firebase/firebase-js-sdk/issues/1176
  if (!('getAll' in firestore)) return Object.assign(firestore, { getAll })
  return firestore
}
exports.default = store
function getAll(...docs) {
  return Promise.all(docs.map(doc => doc.get()))
}
// exports.FirestoreDocumentReference = firebase.firestore.DocumentReference <-- comment this out
// exports.FirestoreTimestamp = firebase.firestore.Timestamp <-- comment this out
// exports.FirestoreFieldValue = firebase.firestore.FieldValue <-- comment this out
//# sourceMappingURL=browser.js.map

```

if I could just pass the database instance (as proposed on #7) and these lines I commented out were lazy getters the problem would kind of go away.

I tried a couple of things on my fork but the only fix would be to export "typesaurus-gatsby" where both adaptors use firebase-admin.

**Comment by lucasavila00** [comment]
The problem is really with how gatsby builts the site with webpack, not with typesaurus.

I did not create the issue hoping the fix would come soon but more as an umbrella for the issue and to have a place where people could document how they worked around the issue.

Given how complicated webpack is I was hoping to not touch their code and focus on creating a workaround with typesaurus.

If typesaurus would like to support gatsby then we could integrate the workaround in typesaurus' build process.

If it's not a goal of this library then I'd have to mantain a fork myself because I need it :/

The minimal example is here: https://github.com/lucasavila00/gatsby-typesaurus-err-sample

**Comment by kossnocorp** [comment]
@lucasavila00 I'll be glad to add the Gatsby support if it doesn't disturb normal usage of the library.

But before I want to get to the bottom of this. I use webpack to build universal Firebase apps and never had problems with webpack compiling that. Maybe there's something in Gatsby's configuration that prevents it from working normally?

**Comment by lucasavila00** [comment]
I created an issue on Gatsby's repository aswell: https://github.com/gatsbyjs/gatsby/issues/20510
Even though I have been using Gatsby for a while this is the first time I've had issues with the build process so I have no idea how it works.
I'm reading a bit to see if I can figure it out.

**Comment by kossnocorp** [comment]
As I see Gatsby provided a solution using `useEffect`. I don't think that's ideal because that's tiresome to wrap every call in `useTypesaurus` or whatever, but that's the peculiarity of Gatsby's design. I work on a universal Firebase application with SSR and don't have such a problem, so it's not inherently Typesaurus or even Firebase issue.

If you're interested in making and maintaining gatsby-plugin-typesaurus plugin, I will provide support, but as I'm not interested in Gatsby myself, I won't be doing it myself.

I'm closing the issue as I don't see anything actionable from my side, but if you think there's something else I can do, feel free to reopen it.
