### ISSUE TITLE
Doesn't seem to work with Parcel & rewrote my package.json

### ISSUE THREAD

**Issue by pnaylor** [kossnocorp/typesaurus#34]
Getting this error and warnings when trying to add Typesaurus [1.12] to my project built with Parcel.

From Browser:
> Error: ENOENT: no such file or directory, open '[..]\app\node_modules\typesaurus\remove\index.js'

After starting in terminal and seeing the following output:
> parcel public/index.html

Server running at http://localhost:1234 
‼  Could not load source file "../src/index.ts" in source map of "../node_modules/typesaurus/index.js".
‼  Could not load source file "../../src/cursor/index.ts" in source map of "../node_modules/typesaurus/cursor/index.js".
‼  Could not load source file "../../src/field/index.ts" in source map of "../node_modules/typesaurus/field/index.js".
‼  Could not load source file "../../src/collection/index.ts" in source map of "../node_modules/typesaurus/collection/index.js".
‼  Could not load source file "../../src/get/index.ts" in source map of "../node_modules/typesaurus/get/index.js".
‼  Could not load source file "../../src/limit/index.ts" in source map of "../node_modules/typesaurus/limit/index.js".
‼  Could not load source file "../../src/group/index.ts" in source map of "../node_modules/typesaurus/group/index.js".
‼  Could not load source file "../../src/ref/index.ts" in source map of "../node_modules/typesaurus/ref/index.js".
‼  Could not load source file "../../src/set/index.ts" in source map of "../node_modules/typesaurus/set/index.js".
‼  Could not load source file "../../src/where/index.ts" in source map of "../node_modules/typesaurus/where/index.js".
‼  Could not load source file "../../src/subcollection/index.ts" in source map of "../node_modules/typesaurus/subcollection/index.js".
‼  Could not load source file "../../src/update/index.ts" in source map of "../node_modules/typesaurus/update/index.js".
‼  Could not load source file "../../src/remove/index.ts" in source map of "../node_modules/typesaurus/remove/index.js".
‼  Could not load source file "../../src/batch/index.ts" in source map of "../node_modules/typesaurus/batch/index.js".
‼  Could not load source file "../../src/onQuery/index.ts" in source map of "../node_modules/typesaurus/onQuery/index.js".
‼  Could not load source file "../../src/query/index.ts" in source map of "../node_modules/typesaurus/query/index.js".
‼  Could not load source file "../../src/getMany/index.ts" in source map of "../node_modules/typesaurus/getMany/index.js".
‼  Could not load source file "../../src/value/index.ts" in source map of "../node_modules/typesaurus/value/index.js".
‼  Could not load source file "../../src/doc/index.ts" in source map of "../node_modules/typesaurus/doc/index.js".
‼  Could not load source file "../../src/transaction/index.ts" in source map of "../node_modules/typesaurus/transaction/index.js".
‼  Could not load source file "../../src/add/index.ts" in source map of "../node_modules/typesaurus/add/index.js".
‼  Could not load source file "../../src/data/index.ts" in source map of "../node_modules/typesaurus/data/index.js".
‼  Could not load source file "../../src/adaptor/browser.ts" in source map of "../node_modules/typesaurus/adapt‼  Could not load source file "../src/index.ts" in source map of "../node_modules/typesaurus/index.js".
‼  Could not load source file "../../src/cursor/index.ts" in source map of "../node_modules/typesaurus/cursor/index.js".
‼  Could not load source file "../../src/get/index.ts" in source map of "../node_modules/typesaurus/get/index.js".
‼  Could not load source file "../../src/collection/index.ts" in source map of "../node_modules/typesaurus/collection/index.js".
‼  Could not load source file "../../src/field/index.ts" in source map of "../node_modules/typesaurus/field/index.js".
‼  Could not load source file "../../src/limit/index.ts" in source map of "../node_modules/typesaurus/limit/index.js".
‼  Could not load source file "../../src/group/index.ts" in source map of "../node_modules/typesaurus/group/index.js".
‼  Could not load source file "../../src/where/index.ts" in source map of "../node_modules/typesaurus/where/index.js".
‼  Could not load source file "../../src/ref/index.ts" in source map of "../node_modules/typesaurus/ref/index.js".
‼  Could not load source file "../../src/set/index.ts" in source map of "../node_modules/typesaurus/set/index.js".
‼  Could not load source file "../../src/subcollection/index.ts" in source map of "../node_modules/typesaurus/subcollection/index.js".
‼  Could not load source file "../../src/update/index.ts" in source map of "../node_modules/typesaurus/update/index.js".
‼  Could not load source file "../../src/batch/index.ts" in source map of "../node_modules/typesaurus/batch/index.js".
‼  Could not load source file "../../src/remove/index.ts" in source map of "../node_modules/typesaurus/remove/index.js".
‼  Could not load source file "../../src/onQuery/index.ts" in source map of "../node_modules/typesaurus/onQuery/index.js".
‼  Could not load source file "../../src/value/index.ts" in source map of "../node_modules/typesaurus/value/index.js".
‼  Could not load source file "../../src/getMany/index.ts" in source map of "../node_modules/typesaurus/getMany/index.js".
‼  Could not load source file "../../src/doc/index.ts" in source map of "../node_modules/typesaurus/doc/index.js".
‼  Could not load source file "../../src/transaction/index.ts" in source map of "../node_modules/typesaurus/transaction/index.js".
‼  Could not load source file "../../src/add/index.ts" in source map of "../node_modules/typesaurus/add/index.js".
‼  Could not load source file "../../src/data/index.ts" in source map of "../node_modules/typesaurus/data/index.js".
‼  Could not load source file "../../src/query/index.ts" in source map of "../node_modules/typesaurus/query/index.js".
‼  Could not load source file "../../src/adaptor/utils.ts" in source map of "../node_modules/typesaurus/adaptor/utils.js".
npm WARN app No repository field.

Have not done much other than try to import the library, create a collection reference and add a document.

Also seeing a very odd side-effect, after getting this error my package.json file has been rewritten to contain only the following:
```
{
  "devDependencies": {
    "typescript": "^3.8.3"
  }
}
```

Would love to use this library if there is a solution. Maybe I just need to add a tsconfig flag or something?

Thanks, best.

**Comment by kossnocorp** [comment]
Hey! That's all sounds weird, especially the bit about rewriting the package.json, there's definitely no code in Typesaurus that can do that.

I reckon it's a Parcel quirk, but I'm not sure.

> Error: ENOENT: no such file or directory, open  '[..]\app\node_modules\typesaurus\remove\index.js'

Could you please check if the `node_modules\typesaurus\remove\index.js` actually in place?

Regarding the source file warnings, it looks like TS doesn't build them properly. I've created an issue for that: https://github.com/kossnocorp/typesaurus/issues/35

**Comment by kossnocorp** [comment]
I believe it's not relevant anymore
