### ISSUE TITLE
Allow Firebase peer dependency with version 7

### ISSUE THREAD

**Issue by whaatt** [kossnocorp/typesaurus#5]
Hi there! Would it be possible to allow Firebase version 7 in the peer dependencies? It doesn't look like any of the breaking changes would affect this library.

Thanks!

https://github.com/kossnocorp/typesaurus/blob/b9d6b7e3881b0394ccf976fe4e77aa77acf8dfce/package.json#L46

**Comment by kossnocorp** [comment]
Hey! Sorry for the long response I wasn't subscribed for the notifications for some reason 😔

That's a good point, I'll make the dependency requirements looser.

**Comment by kossnocorp** [comment]
I've shipped the change with v2.1.0
