### ISSUE TITLE
Add note about using with Next.js

### ISSUE THREAD

**Issue by kossnocorp** [kossnocorp/typesaurus#50]
At the moment the only option to make Typesaurus work with Next.js is to add this command to `package.json`:

```
"postinstall": "echo '{\"main\":\"./browser/index\"}' > node_modules/typesaurus/adaptor/package.json"
```

See for more info: https://github.com/kossnocorp/typesaurus/issues/49

**Comment by locona** [comment]
Hi, @kossnocorp 

When used with SSR in Next.js, the authentication set in `Security Rule` (request.auth ! = null) does not pass.

As a solution, I would like to remove `postinstall` and use firebase-admin in SSR.

If there is another solution, could you please let me know?

**Comment by kossnocorp** [comment]
It's not relevant anymore.

If you want to know about the Next.js integration, please see the guide: https://typesaurus.com/integrations/nextjs/

If you have a problem, please open a separate issue. Thanks!
