### ISSUE TITLE
realtime: to destroy /unsubscribe 

### ISSUE THREAD

**Issue by joshua1** [kossnocorp/typesaurus#55]
Hi @kossnocorp, is there a way to unsubscribe from onQuery,onGet,onAll when certain query parameters are no longer available for e.g logged in user id (uid). If the realtime modules return a subscription, or promise that isn't a callback function like it currently is, it will be easy to unsubscribe.

**Comment by joshua1** [comment]
@kossnocorp by the above I mean have onAll,onGet,onQuery return a subscription, instead of taking callback functions for onResult and onError. makes it easy to unsubscribe later when the subscription is no longer needed. e.g when onAuthStateChange event is fired and the user is no longer logged in, you want to unsubscribe from certain stores that require an active logged in user

**Comment by kossnocorp** [comment]
Hey! Sorry I missed the issue 😵

All of those functions return unsubscribe function that you can use to unsubscribe from the data updates.

**Comment by joshua1** [comment]
Thanks, @kossnocorp, that is helpful

**Comment by kossnocorp** [comment]
Please forgive me again. My email is a mess 😂

I'm wondering if, by any chance, you use React? I have a set of hooks that could make it easier to manage subscriptions.

**Comment by joshua1** [comment]
@kossnocorp  No, I am currently using svelte. I saw the project leveraging react hooks

**Comment by kossnocorp** [comment]
Oh, sweet!
