### ISSUE TITLE
Ability to pass options to operations

### ISSUE THREAD

**Issue by mwood23** [kossnocorp/typesaurus#56]
Awesome work on the library! For my app, it's common that I'll want to set data, but I'm not sure if it exists or not. Firebase handles this with passing `{merge: true}` to the set command. I looked and it didn't look possible right now.

https://firebase.google.com/docs/firestore/manage-data/add-data

Is that something you'd be interested in supporting? If you give me some direction I'd be happy to drop a PR.

**Comment by mwood23** [comment]
Nevermind, found `upset`. Thanks!

**Comment by kossnocorp** [comment]
Hey! I'm glad you liked it!
