### ISSUE TITLE
Transaction API features

### ISSUE THREAD

**Issue by whaatt** [kossnocorp/typesaurus#6]
Hi there (and sorry for creating all the issues)!

I noticed that the transaction API in `typesaurus` doesn't support querying within a transaction. In the types for Firestore, they [allow](https://github.com/googleapis/nodejs-firestore/blob/a425b8b50740d1ab0f07c1b657abed8d5dcea8a8/types/firestore.d.ts#L262) `transaction.get` to take a query object (and acquire pessimistic locks on all the returned documents).

Adding `query` to the transaction API seems straightforward enough; is this something that could be added in the near-term?

Also, please let me know if I could help out with this task.

**Comment by whaatt** [comment]
Also (and maybe this should be in a separate issue): Can the return type of `transaction` be parametrized by some `T`?  Firebase [recommends](https://cloud.google.com/firestore/docs/manage-data/transactions) passing information out of transactions using the return value (which probably should be well-typed).

**Comment by whaatt** [comment]
One more idea I had: Firestore enforces that all reads precede all writes in a transaction. It seems like this could be enforced via types, by having `transaction` take two functions: one that performs reads (and only has access to `t.get` and `t.query`), and one that takes results from the read function and performs writes (with access to `t.update` and `t.remove`).

But maybe this is beyond the scope of the library?

**Comment by kossnocorp** [comment]
> Hi there (and sorry for creating all the issues)!

No worries, thank you for taking the time and share your ideas. As I said in another issue I didn't receive notifications, so sorry for the long response. I really appreciate your interest in the library!

> I noticed that the transaction API in `typesaurus` doesn't support querying within a transaction. In the types for Firestore, they [allow](https://github.com/googleapis/nodejs-firestore/blob/a425b8b50740d1ab0f07c1b657abed8d5dcea8a8/types/firestore.d.ts#L262) `transaction.get` to take a query object (and acquire pessimistic locks on all the returned documents).

Wow, I didn't know that. Weird that it's not mentioned in the docs or simply missed it when worked on the function.

Do you know if it's supported by the web version as well?

> Also, please let me know if I could help out with this task.

I'll be really happy, contributions are very welcome 🙏

**Comment by kossnocorp** [comment]
> Also (and maybe this should be in a separate issue): Can the return type of `transaction` be parametrized by some `T`?  Firebase [recommends](https://cloud.google.com/firestore/docs/manage-data/transactions) passing information out of transactions using the return value (which probably should be well-typed).

Good point, I've created a separate issue for that: https://github.com/kossnocorp/typesaurus/issues/8

**Comment by kossnocorp** [comment]
> One more idea I had: Firestore enforces that all reads precede all writes in a transaction. It seems like this could be enforced via types, by having `transaction` take two functions: one that performs reads (and only has access to `t.get` and `t.query`), and one that takes results from the read function and performs writes (with access to `t.update` and `t.remove`).

> But maybe this is beyond the scope of the library?

That's an interesting idea and might help new developers. When I just started with Firestore I remember how I was confused by the transaction limitations.

How do you the API? Maybe something like this?

```ts
transaction({
  read: t => { /* ... */ },
  write: (readResults, t) => { /* ... */ } 
})
```

I've created an issue for that: https://github.com/kossnocorp/typesaurus/issues/9

**Comment by whaatt** [comment]
Yep, something like that would be great!

**Comment by niklasravnsborg** [comment]
@whaatt @kossnocorp Working with the API now, it would be very cool if every Typesaurus function returns an interface or some kind of typed object. For example I'm using the `batch()` function and need to pass it to multiple consumer functions as an argument. It would be very helpful for me if I could define this input argument with some kind of type.

For example: 

```ts

import { batch, Batch } from 'typesaurus'

const foo = (batch: Batch) => {
  batch.set(...)
  batch.commit(...)
}

const myBatch: Batch = batch()
foo(myBatch)

```

Greetings :)

**Comment by kossnocorp** [comment]
Closing the issue as I addressed all the feedback, thank you a lot @whaatt!
