### ISSUE TITLE
How to use with "FieldValue.increment" etc.

### ISSUE THREAD

**Issue by TheBestMoshe** [kossnocorp/typesaurus#62]
I have a number field, and I would like to increment it with `FieldValue.increment`. However, doing so causes a type error. To fix the type error, I cast the `FieldValue` `as unknown as number`
```
{
    key: (admin.firestore.FieldValue.increment(
            <value to increment by>
          ) as unknown) as number
}
```
However, in Firestore, the value gets converted into a `map` with a key of `operand`
```
Firestore document:

{
    key: {
        operand: <value to increment by>
    }
}
```

Any suggestions?

**Comment by kossnocorp** [comment]
Hey! There's [`value` function for that](https://typesaurus.com/modules/_value_index_.html#value): 

```ts
// Add +4 to the counter field:
update(ref, { counter: value('increment', 4) })
```
