### ISSUE TITLE
How to update nested maps

### ISSUE THREAD

**Issue by TheBestMoshe** [kossnocorp/typesaurus#72]
I am trying to update a nested map. In Firestore SDK you would do
```
// Firestore data:
{
first: {
    test: aaaaa,
    test2: cccc
    }
}

// Firestore SDK
var setAda = dbFirestore.collection('users').doc('alovelace').update({
    "first.test": "12345"
});
```
(See this answer: https://stackoverflow.com/a/49151326/9642772)

How would I do with typesaurus?

I'm pretty sure this I should be using [Fields](https://typesaurus.com/modules/_field_index_.html#field-1). However, I can't figure out the exact syntax. Any help would be appreciated.

**Comment by SrBrahma** [comment]
You can do it by

```ts
update(myCollection, myDocId, {'first.second': value})
```

If you need a dynamic key, like having a variable inside (like ids), you can

```ts
update(myCollection, myDocId, {[`first.second.${myId}`]: value})
```

**Comment by SrBrahma** [comment]
Actually, the above is only TS-allowed on transactions. For update outside transactions, you can do this:

```update(myCollection, myDocId, [field(['first', 'second'], value)]);```

**Comment by kossnocorp** [comment]
Now it's possible with v10, see: https://typesaurus.com/api/writing/update/#field
