### ISSUE TITLE
Unexpected token *

### ISSUE THREAD

**Issue by bradkyle** [kossnocorp/typesaurus#83]
Get the following error when trying to use typesaurus with google cloud functions:

> Detailed stack trace: /srv/node_modules/@google-cloud/firestore/build/src/collection-group.js:55
>         async *getPartitions(desiredPartitionCount) {
>               ^
> 
>  SyntaxError: Unexpected token *
>         at createScript (vm.js:80:10)
>         at Object.runInThisContext (vm.js:139:10)
>         at Module._compile (module.js:617:28)
>         at Object.Module._extensions..js (module.js:664:10)
>         at Module.load (module.js:566:32)
>         at tryModuleLoad (module.js:506:12)
>         at Function.Module._load (module.js:498:3)
>         at Module.require (module.js:597:17)
>         at require (internal/module.js:11:18)
>         at Object.<anonymous> (/srv/node_modules/@google-cloud/firestore/build/src/index.js:39:28).

The offending code:

```
import * as t from 'typesaurus'
...
interface User {
	userId?     : string;
	email?       :	string;
	phone?      :	string;
}
// -- or --
 type User = {
        userId?     : string; 
        email? 		  :	string;
        phone?      :	string;
}
...
firebase.initializeApp(firebaseConfig)
const users = t.collection<user.User>('users');

```

Does anyone know what the cause of this could be?
Thanks

**Comment by kossnocorp** [comment]
This error is coming from [@google-cloud/firestore](https://www.npmjs.com/package/@google-cloud/firestore). It appears that you have an old Node.js runtime, where the generators (* symbol) or async/await are not supported. What's your Node.js version?

**Comment by kossnocorp** [comment]
Hey, did you manage to figure out the problem?

**Comment by kossnocorp** [comment]
It appears not to be a Typesaurus issue, but please reopen it with more details about the problem if you still think it is.
