### ISSUE TITLE
🔥 Want to help Typesaurus? I'm looking for core contributors

### ISSUE THREAD

**Issue by kossnocorp** [kossnocorp/typesaurus#85]
Hey!

If you use Firestore and TypeScript in day-to-day work and want to help make Typesaurus better, ping me at koss@nocorp.me or sending me DM https://twitter.com/kossnocorp.

Thanks,
Sasha

**Comment by zhenhao18** [comment]
Hi man, 

I am interested in this idea! I was used to mongoose and mongoDB, looking for similar ones, and typeSaurus is the one.
How should I work on this project?

Regards
Zhen

**Comment by mparpaillon** [comment]
Count me in :)

**Comment by kossnocorp** [comment]
It's not really relevant anymore, but feel free to ping me if you want to contribute
