### ISSUE TITLE
'ref(users).id' is throwing an error. 

### ISSUE THREAD

**Issue by utb2017** [kossnocorp/typesaurus#86]
```
type User = { name: string }
const users = collection<User>('users')

const id = ref(users).id  **error here**
set(users, id, {name: 'John Doe'})
```

I can see that it says it will create an ID when one is not supplied. However, I can't get it to upload to google cloud functions without running into this error. Visual Studio is throwing an error too.

```
Expected 2 arguments, but got 1 .ts(2554)
index.d.ts(47, 3):  An argument for 'id' was not provided.
```

**Comment by kossnocorp** [comment]
Hey! As the error says, you must provide the id: `ref(users, 'some-id')`. If you want to simply add a document, use add instead: `set(users, {name: 'John Doe'})`. It will return you a ref with an automatically assigned id.

If for some reason you must generate id beforehand, you can use `id` function: https://typesaurus.com/modules/_ref_index_.html#id (note that it's an async function), or nanoid: https://github.com/ai/nanoid (which is sync).

**Comment by utb2017** [comment]
The link you gave '_ref_index_' brings me to the code I posted above. The code I posted above isn't passing tslint.

```
> tsc

src/requests/createCoupon.ts:120:20 - error TS2554: Expected 2 arguments, but got 1.

120         const id = ref(users).id
                       ~~~~~~~~~~

  node_modules/typesaurus/ref/index.d.ts:47:3
    47   id: string
         ~~~~~~~~~~
    An argument for 'id' was not provided.
```

**Comment by kossnocorp** [comment]
> The link you gave 'ref_index' brings me to the code I posted above

I see. The link leads to `id`, but now I can see that it contains an outdated example. Sorry about that.

> While I am here, I get errors if I try to query with "in", ex. where('role', 'in',[ 'manager','driver'] ).

To make it work, the role field in the collection you query should extend `'manager' | 'driver'`

> I also could not figure out the collectionGroup implementation. ex db.collectionGroup('Discounts').where('id', '==', id).get()

Check `group` function that creates a collection that you can query: https://typesaurus.com/modules/_group_index_.html#group

**Comment by utb2017** [comment]
I figured out the  `where('role', 'in',[ 'manager','driver'] )` with a version update.

**Comment by kossnocorp** [comment]
It's not relevant anymore and has been fixed in v10
