### ISSUE TITLE
saving `serverTimestamp()` not working as expected

### ISSUE THREAD

**Issue by skwny** [kossnocorp/typesaurus#90]
When using `firebase.firestore.FieldValue.serverTimestamp()`, the saved data results in:

![image](https://user-images.githubusercontent.com/13693304/120028776-012cf080-bfaa-11eb-803e-2a0115bc5155.png)

I've tried saving this via `set(doc, id, data)` as well as `db.doc(ref).set(data)` using the same ref and data, and only the latter method saves in the appropriate format, ie:

![image](https://user-images.githubusercontent.com/13693304/120029031-61bc2d80-bfaa-11eb-9f13-4531aa5cec13.png)

Is there another way that the Firestore Timestamp must be generated for Typesaurus?

**Comment by kossnocorp** [comment]
Hey, sorry about that. You should use [`value('serverDate')`](https://typesaurus.com/modules/_value_index_.html#value) instead of the native `FieldValue`.
