### ISSUE TITLE
Support for firebase 9

### ISSUE THREAD

**Issue by buster95** [kossnocorp/typesaurus#99]
I'm trying to use typesaurus with firebase 9 but doesn't have support, is there a possibility to configure typesaurus with a custom adapter for firestore??

SS when I configure firebase
![image](https://user-images.githubusercontent.com/15637669/132973776-004749e0-7646-4c92-86bc-4f21a6f4172c.png)

SS about mistake
![image](https://user-images.githubusercontent.com/15637669/132973722-ad33e02a-ac92-4773-8b00-c01f568635ef.png)

**Comment by xbaun** [comment]
I tried to upgrade [typesaurus to v9](https://github.com/xbaun/typesaurus/commits/fbv9), but with the current typesaurus code base it's only possible to use firebase v9 in compat mode (which isn't compatible to new v9 api).

It appears that either the typesaurus adapter or all typesaurus functions need to be adjusted to reflect the new v9 api. Another problem, I think, is that firebase-admin and firebase@v9 (without compat) no longer share the same API and thus typesaurus no longer work isomporphically between browser and node env.

You can try firebase v9 in compat mode with my fork by declaring in package.json:
```json
"dependencies": {
    "typesaurus": "https://github.com/xbaun/typesaurus-pkg.git"
}
```

**Comment by SrBrahma** [comment]
@xbaun looks good but you built in on top of master branch instead of the incoming v8: https://github.com/kossnocorp/typesaurus/tree/v8

@kossnocorp

**Comment by kossnocorp** [comment]
Sorry, guys for the silence, v9 support is coming.

**Comment by kossnocorp** [comment]
Shipped with v10
